package com.example.expressora.models

import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

data class Notification(
    val id: String = "", // Auto-generated by Firestore
    val userId: String = "",
    val userEmail: String = "",
    val title: String = "",
    val message: String = "",
    val type: String = "", // "achievement", "quiz_completion", etc.
    val isRead: Boolean = false,
    @ServerTimestamp
    val createdAt: Date? = null
)

